# Generated by Django 3.2.4 on 2021-06-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Book Title', max_length=100)),
                ('author', models.CharField(help_text='Book Author', max_length=100)),
                ('description', models.TextField()),
                ('book_link', models.CharField(help_text='Book Link', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('image', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
